/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Book = {
  _id: string
  _type: 'book'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  datePublished?: string
  isbn?: string
  publisher?: string
  genre?:
    | 'art and design'
    | 'biographies and memoires'
    | 'comics'
    | 'fiction'
    | 'humor'
    | 'mystery'
    | 'nonfiction'
    | 'poetry'
    | 'reference'
    | 'science fiction'
    | 'uncategorized'
    | 'youth fiction'
  typefaces?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'typeface'
  }>
  images: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  designers?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  authors?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  illustrators?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  artDirectors?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  photographers?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  legacyId?: string
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  homepage?: string
}

export type Typeface = {
  _id: string
  _type: 'typeface'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug: Slug
  name: string
  url?: string
}

export type Genre = {
  _id: string
  _type: 'genre'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug: Slug
  name: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Book
  | Person
  | Typeface
  | Genre
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/queries/books.ts
// Variable: bookQuery
// Query: *[_type == 'book' && slug.current == $slug][0]{    ...,    notes[],    designers[] -> {      name    },    authors[] -> {      name    },    illustrators[] -> {      name    },    artDirectors[] -> {      name    },    photographers[] -> {      name    },    images[] {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}  }
export type BookQueryResult = {
  _id: string
  _type: 'book'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  datePublished?: string
  isbn?: string
  publisher?: string
  genre?:
    | 'art and design'
    | 'biographies and memoires'
    | 'comics'
    | 'fiction'
    | 'humor'
    | 'mystery'
    | 'nonfiction'
    | 'poetry'
    | 'reference'
    | 'science fiction'
    | 'uncategorized'
    | 'youth fiction'
  typefaces?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'typeface'
  }>
  images: Array<{
    asset: {
      metadata: {
        lqip: string | null
        blurHash: string | null
        dimensions: SanityImageDimensions | null
      } | null
      originalFilename: string | null
      url: string | null
    } | null
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  designers: Array<{
    name: string
  }> | null
  authors: Array<{
    name: string
  }> | null
  illustrators: Array<{
    name: string
  }> | null
  artDirectors: Array<{
    name: string
  }> | null
  photographers: Array<{
    name: string
  }> | null
  notes: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }> | null
  legacyId?: string
} | null
// Variable: booksQuery
// Query: {    "books": *[_type == 'book'] | order(datePublished desc) [$start...$end] {      ...,      notes[],      designers[] -> {        name      },      authors[] -> {        name      },      "cover": images[0] {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}    },    "total": count(*[_type == 'book'])  }
export type BooksQueryResult = {
  books: Array<{
    _id: string
    _type: 'book'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title: string
    slug: Slug
    datePublished?: string
    isbn?: string
    publisher?: string
    genre?:
      | 'art and design'
      | 'biographies and memoires'
      | 'comics'
      | 'fiction'
      | 'humor'
      | 'mystery'
      | 'nonfiction'
      | 'poetry'
      | 'reference'
      | 'science fiction'
      | 'uncategorized'
      | 'youth fiction'
    typefaces?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'typeface'
    }>
    images: Array<{
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }>
    designers: Array<{
      name: string
    }> | null
    authors: Array<{
      name: string
    }> | null
    illustrators?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    artDirectors?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    photographers?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    notes: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }> | null
    legacyId?: string
    cover: {
      asset: {
        metadata: {
          lqip: string | null
          blurHash: string | null
          dimensions: SanityImageDimensions | null
        } | null
        originalFilename: string | null
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    } | null
  }>
  total: number
}
// Variable: bookIndexQuery
// Query: {    "books": *[_type == 'book'] | order(datePublished desc) [$start...$end] {      title,      slug,      datePublished,      designers[] -> {        name      },      "image": images[0] {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}    },    "total": count(*[_type == 'book'])  }
export type BookIndexQueryResult = {
  books: Array<{
    title: string
    slug: Slug
    datePublished: string | null
    designers: Array<{
      name: string
    }> | null
    image: {
      asset: {
        metadata: {
          lqip: string | null
          blurHash: string | null
          dimensions: SanityImageDimensions | null
        } | null
        originalFilename: string | null
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    } | null
  }>
  total: number
}

// Source: ./src/sanity/queries/persons.ts
// Variable: personQuery
// Query: *[_type == 'person' && slug.current == $slug][0]{    ...,    "books": *[_type == "book" && references(^._id)] | order(datePublished desc)  {      ...,      images[] {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}    }  }
export type PersonQueryResult = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  homepage?: string
  books: Array<{
    _id: string
    _type: 'book'
    _createdAt: string
    _updatedAt: string
    _rev: string
    title: string
    slug: Slug
    datePublished?: string
    isbn?: string
    publisher?: string
    genre?:
      | 'art and design'
      | 'biographies and memoires'
      | 'comics'
      | 'fiction'
      | 'humor'
      | 'mystery'
      | 'nonfiction'
      | 'poetry'
      | 'reference'
      | 'science fiction'
      | 'uncategorized'
      | 'youth fiction'
    typefaces?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'typeface'
    }>
    images: Array<{
      asset: {
        metadata: {
          lqip: string | null
          blurHash: string | null
          dimensions: SanityImageDimensions | null
        } | null
        originalFilename: string | null
        url: string | null
      } | null
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }>
    designers?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    authors?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    illustrators?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    artDirectors?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    photographers?: Array<{
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'person'
    }>
    notes?: Array<{
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }>
    legacyId?: string
  }>
} | null
// Variable: personIndexQuery
// Query: *[_type == 'person'] | order(name desc) {    ...  }
export type PersonIndexQueryResult = Array<{
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  homepage?: string
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    "\n  *[_type == 'book' && slug.current == $slug][0]{\n    ...,\n    notes[],\n    designers[] -> {\n      name\n    },\n    authors[] -> {\n      name\n    },\n    illustrators[] -> {\n      name\n    },\n    artDirectors[] -> {\n      name\n    },\n    photographers[] -> {\n      name\n    },\n    images[] \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n  }\n": BookQueryResult
    '\n  {\n    "books": *[_type == \'book\'] | order(datePublished desc) [$start...$end] {\n      ...,\n      notes[],\n      designers[] -> {\n        name\n      },\n      authors[] -> {\n        name\n      },\n      "cover": images[0] \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n    },\n    "total": count(*[_type == \'book\'])\n  }\n': BooksQueryResult
    '\n  {\n    "books": *[_type == \'book\'] | order(datePublished desc) [$start...$end] {\n      title,\n      slug,\n      datePublished,\n      designers[] -> {\n        name\n      },\n      "image": images[0] \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n    },\n    "total": count(*[_type == \'book\'])\n  }\n': BookIndexQueryResult
    '\n  *[_type == \'person\' && slug.current == $slug][0]{\n    ...,\n    "books": *[_type == "book" && references(^._id)] | order(datePublished desc)  {\n      ...,\n      images[] \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n    }\n  }\n': PersonQueryResult
    "\n  *[_type == 'person'] | order(name desc) {\n    ...\n  }\n": PersonIndexQueryResult
  }
}
