/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Book = {
  _id: string
  _type: 'book'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  legacyId?: string
  isbn?: string
  genre?:
    | 'art and design'
    | 'biographies and memoires'
    | 'comics'
    | 'fiction'
    | 'humor'
    | 'mystery'
    | 'nonfiction'
    | 'poetry'
    | 'reference'
    | 'science fiction'
    | 'uncategorized'
    | 'youth fiction'
  typefaces?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'typeface'
  }>
  images: Array<{
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
    _key: string
  }>
  designers?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  authors?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  illustrators?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  artDirectors?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
  photographers?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'person'
  }>
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug: Slug
  name: string
  homepage?: string
}

export type Typeface = {
  _id: string
  _type: 'typeface'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug: Slug
  name: string
  url?: string
}

export type Genre = {
  _id: string
  _type: 'genre'
  _createdAt: string
  _updatedAt: string
  _rev: string
  slug: Slug
  name: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AllSanitySchemaTypes =
  | Book
  | Person
  | Typeface
  | Genre
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./src/sanity/queries/Metadata.ts
// Variable: metadataQuery
// Query: *[(_type == 'page') && metadata.slug.current == $slug][0]{    metadata {      ...,      image {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}    }  }
export type MetadataQueryResult = null

// Source: ./src/sanity/queries/navigation.ts
// Variable: navigationQuery
// Query: *[_type == 'navigation' && slug.current == $slug][0]{    ...,    links[] {      ...,      link {        ...,        internalLink -> {          metadata        }      }    }  }
export type NavigationQueryResult = null

// Source: ./src/sanity/queries/page.ts
// Variable: pageQuery
// Query: *[_type == 'page' && metadata.slug.current == $slug][0]{    metadata {      ...    },    modules[] {      ...,      slides[] {        ...,        cta {          ...,          link {  ...,  internalLink -> {    _type,    _id,    publishDate,    metadata {      title,      slug {        current      }    }  }}        },        image {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}      },      logos[] {        ...,        logo {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}      },      image {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }},      images[] {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }},      cards[] {        ...,        image {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }}      },      columns[] {        ...,        image {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }},        cta {          ...,          link {  ...,  internalLink -> {    _type,    _id,    publishDate,    metadata {      title,      slug {        current      }    }  }},        }      },      cta {        ...,        link {  ...,  internalLink -> {    _type,    _id,    publishDate,    metadata {      title,      slug {        current      }    }  }}      }    }  }
export type PageQueryResult = null
// Variable: pageIndexQuery
// Query: *[_type == 'page']{    _updatedAt,    metadata {      ...    }  }
export type PageIndexQueryResult = Array<never>

// Source: ./src/sanity/queries/siteSettings.ts
// Variable: siteSettingsQuery
// Query: *[_type == 'siteSettings'][0]{    title,    description,    shareImage {  ...,  asset-> {    metadata {      lqip,      blurHash,      dimensions    },    originalFilename,    url  }},    socialLinks[] {      _key,      label,      iconKey,      link {  ...,  internalLink -> {    _type,    _id,    publishDate,    metadata {      title,      slug {        current      }    }  }}    },    navigation[] {      _key,      label,      link {  ...,  internalLink -> {    _type,    _id,    publishDate,    metadata {      title,      slug {        current      }    }  }}    }  }
export type SiteSettingsQueryResult = null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    "\n  *[(_type == 'page') && metadata.slug.current == $slug][0]{\n    metadata {\n      ...,\n      image \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n    }\n  }\n": MetadataQueryResult
    "\n  *[_type == 'navigation' && slug.current == $slug][0]{\n    ...,\n    links[] {\n      ...,\n      link {\n        ...,\n        internalLink -> {\n          metadata\n        }\n      }\n    }\n  }\n": NavigationQueryResult
    "\n  *[_type == 'page' && metadata.slug.current == $slug][0]{\n    metadata {\n      ...\n    },\n    modules[] {\n      ...,\n      slides[] {\n        ...,\n        cta {\n          ...,\n          link \n{\n  ...,\n  internalLink -> {\n    _type,\n    _id,\n    publishDate,\n    metadata {\n      title,\n      slug {\n        current\n      }\n    }\n  }\n}\n\n        },\n        image \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n      },\n      logos[] {\n        ...,\n        logo \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n      },\n      image \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n,\n      images[] \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n,\n      cards[] {\n        ...,\n        image \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n\n      },\n      columns[] {\n        ...,\n        image \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n,\n        cta {\n          ...,\n          link \n{\n  ...,\n  internalLink -> {\n    _type,\n    _id,\n    publishDate,\n    metadata {\n      title,\n      slug {\n        current\n      }\n    }\n  }\n}\n,\n        }\n      },\n      cta {\n        ...,\n        link \n{\n  ...,\n  internalLink -> {\n    _type,\n    _id,\n    publishDate,\n    metadata {\n      title,\n      slug {\n        current\n      }\n    }\n  }\n}\n\n      }\n    }\n  }\n": PageQueryResult
    "\n  *[_type == 'page']{\n    _updatedAt,\n    metadata {\n      ...\n    }\n  }\n": PageIndexQueryResult
    "\n  *[_type == 'siteSettings'][0]{\n    title,\n    description,\n    shareImage \n{\n  ...,\n  asset-> {\n    metadata {\n      lqip,\n      blurHash,\n      dimensions\n    },\n    originalFilename,\n    url\n  }\n}\n,\n    socialLinks[] {\n      _key,\n      label,\n      iconKey,\n      link \n{\n  ...,\n  internalLink -> {\n    _type,\n    _id,\n    publishDate,\n    metadata {\n      title,\n      slug {\n        current\n      }\n    }\n  }\n}\n\n    },\n    navigation[] {\n      _key,\n      label,\n      link \n{\n  ...,\n  internalLink -> {\n    _type,\n    _id,\n    publishDate,\n    metadata {\n      title,\n      slug {\n        current\n      }\n    }\n  }\n}\n\n    }\n  }\n": SiteSettingsQueryResult
  }
}
